# Generated by Django 4.2.1 on 2023-06-13 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0001_initial'),
        ('detarticulo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detarticulo',
            name='nombre',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='articulo.articulo'),
        ),
    ]
