# Generated by Django 4.2.1 on 2023-06-13 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detarticulo', '0002_detarticulo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detarticulo',
            name='cantidad',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
